### PR TITLE
For wrong translation used when maya is not set in cm

### PR DESCRIPTION
**Pull request by renaudll**

### CODE REVIEW

**Comment by bhouston** [comment]
Nice.  Should we also be doing this conversion on export as well?

**Comment by bhouston** [comment]
BTW the Alembic file format is actually unitless, which means that it doesn't specify a unit.  This generally means we shouldn't be doing any type of unit conversion for import or export generally.  It is up to the user to be responsible for units.

**Comment by renaudll** [comment]
You are right, however the translation attribute of a maya transform expect the data in the unit size of the scene. Here's some repro-steps that better illustrate the issue.

1) Open maya and set it in meter
2) Create a locator with a translation of 1
3) Export the locator via ExocortexCrate
4) Re-import the locator via ExocortexCrate
5) Notice the locator now have a translation of 100

**Comment by bhouston** [comment]
So I looked a bit more at the code.  I will merge this.  I think the issue is that while we do export without looking at units, we are accessing the transform matrix directly.  When we import, we are specifying a translation, rather than the transform matrix, and I suspect we need to have units on the translation.  Your PR does this.

I didn't realize the translation required units while the transform matrix did not.

**Comment by bhouston** [comment]
Thanks!

**Pull request merged**
